# Generated by Django 6.0.6 on 2026-06-12 07:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('founder_pk', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('founder_code', models.CharField(max_length=20, unique=True)),
                ('founder_name', models.CharField(max_length=200)),
                ('spiritual_name', models.CharField(blank=True, max_length=200, null=True)),
                ('birth_name', models.CharField(blank=True, max_length=200, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('mahasamadhi_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=300, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('founder_message', models.TextField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Founder',
                'verbose_name_plural': 'Founder',
                'db_table': 'founder_master',
            },
        ),
    ]
