# Generated by Django 6.0.6 on 2026-06-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='founder',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
